//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtbCnb2.ZaslaniDat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.ness.cz.ewiautom.wsimpl/IZaslaniDat.wsdl", ConfigurationName="ZaslaniDat.IZaslaniDatPortType")]
    public interface IZaslaniDatPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:com-ness-cz-ewiautom-wsimpl-IZaslaniDat) of message loadDataRequest does not match the default value (http://com.ness.cz.ewiautom.wsimpl/IZaslaniDat.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:com-ness-cz-ewiautom-wsimpl-IZaslaniDat/loadData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        XtbCnb2.ZaslaniDat.loadDataResponse loadData(XtbCnb2.ZaslaniDat.loadDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadData", WrapperNamespace="urn:com-ness-cz-ewiautom-wsimpl-IZaslaniDat", IsWrapped=true)]
    public partial class loadDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string param0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string param1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string param2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string param3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string param4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] param5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string param6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string param7;
        
        public loadDataRequest() {
        }
        
        public loadDataRequest(string param0, string param1, string param2, string param3, string param4, byte[] param5, string param6, string param7) {
            this.param0 = param0;
            this.param1 = param1;
            this.param2 = param2;
            this.param3 = param3;
            this.param4 = param4;
            this.param5 = param5;
            this.param6 = param6;
            this.param7 = param7;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadDataResponse", WrapperNamespace="urn:com-ness-cz-ewiautom-wsimpl-IZaslaniDat", IsWrapped=true)]
    public partial class loadDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public loadDataResponse() {
        }
        
        public loadDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZaslaniDatPortTypeChannel : XtbCnb2.ZaslaniDat.IZaslaniDatPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZaslaniDatPortTypeClient : System.ServiceModel.ClientBase<XtbCnb2.ZaslaniDat.IZaslaniDatPortType>, XtbCnb2.ZaslaniDat.IZaslaniDatPortType {
        
        public ZaslaniDatPortTypeClient() {
        }
        
        public ZaslaniDatPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZaslaniDatPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZaslaniDatPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZaslaniDatPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XtbCnb2.ZaslaniDat.loadDataResponse XtbCnb2.ZaslaniDat.IZaslaniDatPortType.loadData(XtbCnb2.ZaslaniDat.loadDataRequest request) {
            return base.Channel.loadData(request);
        }
        
        public string loadData(string param0, string param1, string param2, string param3, string param4, byte[] param5, string param6, string param7) {
            XtbCnb2.ZaslaniDat.loadDataRequest inValue = new XtbCnb2.ZaslaniDat.loadDataRequest();
            inValue.param0 = param0;
            inValue.param1 = param1;
            inValue.param2 = param2;
            inValue.param3 = param3;
            inValue.param4 = param4;
            inValue.param5 = param5;
            inValue.param6 = param6;
            inValue.param7 = param7;
            XtbCnb2.ZaslaniDat.loadDataResponse retVal = ((XtbCnb2.ZaslaniDat.IZaslaniDatPortType)(this)).loadData(inValue);
            return retVal.@return;
        }
    }
}
